### ISSUE TITLE
Funky on mobile

### ISSUE THREAD

**Issue by AndrewKYang** [AndrewKYang/TRACEWebsite#2]
Need to fix @media tags and percentages in CSS. 
![screen shot 2016-01-25 at 9 50 55 pm](https://cloud.githubusercontent.com/assets/12108342/12572128/c35780ac-c3ad-11e5-910a-63ffb6e31bf2.png)
![screen shot 2016-01-25 at 9 50 44 pm](https://cloud.githubusercontent.com/assets/12108342/12572129/c358dda8-c3ad-11e5-9a21-65ace5f36e5b.png)

**Comment by varunkamath** [comment]
Tentatively closed
